### ISSUE TITLE
No null check. causes app to crash if no music is selected

### ISSUE THREAD

**Issue by VigneshVoid** [SeakyLuo/SMPlayer#1]
`right.Invoked += (sender, args) => MediaHelper.Position = Math.Min(MediaHelper.Position + 5, CurrentMusic.Duration);`

In the above code there seems to be null check isn't there for `CurrentMusic` which causes application to crash.

**Comment by SeakyLuo** [comment]
Thank you for the potential bug! I don't know why but my app doesn't crash though for when I press that key. But still appreciate your bug report!

**Comment by SeakyLuo** [comment]
Fixed!
